main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: Blog
    url: /#news
    weight: 40
  - name: CV
    url: experience/
    weight: 50
